//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCHardwareShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public int LoginTableID { get; set; }
        public Nullable<int> RankTableID { get; set; }
    
        public virtual EmployeeRank EmployeeRank { get; set; }
        public virtual UserLoginTable UserLoginTable { get; set; }
    }
}
