//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System.Xml.Serialization;

namespace PCHardwareShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryLink
    {
        public int ID { get; set; }
        public int pID { get; set; }
        public Nullable<int> pCategory { get; set; }
        //[JsonIgnore, XmlIgnore]
        public virtual Category Category { get; set; }
       // [JsonIgnore, XmlIgnore]
        public virtual Product Product { get; set; }
    }
}
