//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using System.Xml.Serialization;
namespace PCHardwareShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSpecification()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int SpecificationID { get; set; }
        public string Processor { get; set; }
        public string Colors { get; set; }
        public string Display { get; set; }
        public string Memory { get; set; }
        public string Storage { get; set; }
        public string Graphics { get; set; }
        public string OS { get; set; }
        public string Battery { get; set; }
        public string Adapter { get; set; }
        public string Audio { get; set; }
        public string Keyboard { get; set; }
        public string WebCam { get; set; }

        [JsonIgnore, XmlIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
