//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCHardwareShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCode
    {
        public int ID { get; set; }
        public string PromoCode1 { get; set; }
        public Nullable<int> UsageLeft { get; set; }
        public Nullable<int> OfferInPercentage { get; set; }
    }
}
