//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCHardwareShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusTable
    {
        public int ID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string FailedReason { get; set; }
        public string Status { get; set; }
    
        public virtual OrderdUserInfo OrderdUserInfo { get; set; }
    }
}
